### ISSUE TITLE
Facebook login

### ISSUE THREAD

**Issue by ParaschivAlex** [ParaschivAlex/Portal-Doctor-Patient#2]
Eroare la LoginAsync.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.NotImplementedException: The method or operation is not implemented.

Line 90: 		internal Task<IdentityResult> AddLoginAsync(string id, string v) 
Line 91: 		{ 
Line 92: 			throw new NotImplementedException(); 
Line 93: 		} 
Line 94: 	}

**Comment by StaicuBogdan** [comment]
O sa o facem in curand

**Comment by ParaschivAlex** [comment]
Rezolvat, am scos linia unde dadea eroare ca era inutila si am modificat in AccountController linia 375.
